name: zizmor

on:
  pull_request:
  push:
    branches:
      - master

permissions:
  contents: read

jobs:
  zizmor:
    name: GitHub Actions security analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
      - name: Run zizmor
        uses: zizmorcore/zizmor-action@v0.5.6

